/*
 * CalendarView.java
 *
 * Created on December 13, 2002, 8:39 PM
 */

package simpleimap;

import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.text.*;
import javax.swing.*;
import javax.swing.border.*;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.*;

import java.awt.Dimension;

/**
 *
 * @author  hassan
 */
public class CalendarView  extends JPanel implements CalendarModel.CalendarModelListener {
    private DayPanel daysHeader[];
    private DayPanel days[];
    private DayPanel selectedDayItem;
    private int day;
  
    private Color nextMonthColor;
    private Color weekendColor;
    private Color borderColor;
    private Color selectedColor;
    private Color selectedBorderColor;
    private Color highlightedBorderColor;
    private Color textColor;
    private Color labelColor;
    private Color headerColor;
    
    private Color backgroundColor;
    
    private Border selectedBorder;
    private Border regularDayBorder;
    private Border highlightedBorder;
    
    private String dayNames[];
    private String monthNames[];
    
    private Calendar calendar;
    private Calendar today;
    private Calendar selectedDate;

    private Locale locale;
    private boolean initialized = false;
    
    DayMouseListener dayMouseListener;    
    DefaultItem item;
    
    CalendarModel model;
    Color unselectedDayColor;
    Color selectedDayColor;
    
    /** Creates new form CalendarView */
    public CalendarView() {
        super();
        
        this.thePanel = this;
        
        locale = Locale.getDefault();
        days = new DayPanel[6*7];
        daysHeader = new DayPanel[7];
        
        calendar = Calendar.getInstance(locale);
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
        
        
        //Debug.debug("start calendar ", calendar);
        
        TimeZone tz = this.calendar.getTimeZone();
        Debug.debug("TIMEZone=" + tz.toString());
        
        this.today = (Calendar) calendar.clone();
        this.selectedDate = (Calendar) calendar.clone();
        
        this.model = null;
        
        nextMonthColor = new Color(232, 238, 236);
        weekendColor = new Color(255, 249, 239);
        borderColor = new Color(121, 142, 145);
        selectedColor = new Color(214, 227, 243);
        selectedBorderColor = new Color(109, 159, 188);
        highlightedBorderColor = new Color(0,255,0);
        textColor = new Color(0, 0, 0);
        headerColor = new Color(66, 124, 141);
        labelColor = new Color(136,163,180);
        
        backgroundColor = new Color(255, 255, 255);
        
        this.unselectedDayColor = new Color(255, 255, 255);
        this.selectedDayColor = selectedColor;
        
        this.dayMouseListener = new DayMouseListener(this);          
        initComponents();
        
        this.setupMonthViewPanel();
    }
    
    public void setModel(CalendarModel model) {
        if (this.model != null) {
            this.model.removeCalendarListener(this);
        }
        this.model = model;
        this.model.addCalendarListener(this);
        this.monthChanged();
    }
    
    public CalendarModel getModel() {
        return this.model;
    }
    
    public void setViewedItem(CalendarItemModel.ModelItem mi) {
        Date date = new Date();
        date.setTime(mi.date);
        this.showDate(date);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        MonthViewPanel = new javax.swing.JPanel();
        monthHeaderPanel = new javax.swing.JPanel();
        prevButton = new javax.swing.JButton();
        todayButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        monthText = new javax.swing.JLabel();
        yearText = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        MonthPanel = new javax.swing.JPanel();
        DaysHeaderPanel = new javax.swing.JPanel();
        DaysPanel = new javax.swing.JPanel();

        this.thePanel.setLayout(new javax.swing.BoxLayout(this.thePanel, javax.swing.BoxLayout.Y_AXIS));

        // setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //setTitle("Calendar");
        this.thePanel.setBackground(new java.awt.Color(255, 255, 255));
 
        //addWindowListener(new java.awt.event.WindowAdapter() {
        //    public void windowClosing(java.awt.event.WindowEvent evt) {
        //        exitForm(evt);
        //    }
        //});

        MonthViewPanel.setLayout(new java.awt.BorderLayout());

        MonthViewPanel.setBackground(new java.awt.Color(255, 255, 255));
        MonthViewPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(8, 8, 8, 8)));
        MonthViewPanel.setMaximumSize(new java.awt.Dimension(99999, 99999));
        MonthViewPanel.setMinimumSize(new java.awt.Dimension(400, 300));
        MonthViewPanel.setPreferredSize(new java.awt.Dimension(640, 480));
        monthHeaderPanel.setLayout(new java.awt.BorderLayout());

        monthHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        monthHeaderPanel.setMaximumSize(new java.awt.Dimension(32767, 70));
        monthHeaderPanel.setMinimumSize(new java.awt.Dimension(10, 70));
        monthHeaderPanel.setPreferredSize(new java.awt.Dimension(100, 70));
        
        JPanel buttonPanel = new JPanel();
        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setMaximumSize(new java.awt.Dimension(300, 150));
        buttonPanel.setMinimumSize(new java.awt.Dimension(10, 150));
        buttonPanel.setPreferredSize(new java.awt.Dimension(150, 150));        
        buttonPanel.setLayout(new java.awt.BorderLayout());
        
        prevButton.setText("Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(prevButton, java.awt.BorderLayout.WEST);

        todayButton.setText("Today");
        todayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(todayButton, java.awt.BorderLayout.EAST);   
        
        monthHeaderPanel.add(buttonPanel, java.awt.BorderLayout.WEST);
        
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        monthText.setFont(new java.awt.Font("Arial Black", 0, 24));
        monthText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        monthText.setText("MonthText");
        monthText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        monthText.setAlignmentY(0.0F);
        jPanel2.add(monthText, java.awt.BorderLayout.NORTH);

        yearText.setFont(new java.awt.Font("Arial Black", 0, 24));
        yearText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearText.setText("YearText");
        yearText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        yearText.setAlignmentY(0.0F);
        jPanel2.add(yearText, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2);

        monthHeaderPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        monthHeaderPanel.add(nextButton, java.awt.BorderLayout.EAST);

        MonthViewPanel.add(monthHeaderPanel, java.awt.BorderLayout.NORTH);

        MonthPanel.setLayout(new javax.swing.BoxLayout(MonthPanel, javax.swing.BoxLayout.Y_AXIS));

        MonthPanel.setBackground(new java.awt.Color(255, 255, 255));
        MonthPanel.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1))), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0))));
        DaysHeaderPanel.setLayout(new java.awt.GridLayout(1, 7));

        DaysHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        DaysHeaderPanel.setMaximumSize(new java.awt.Dimension(32767, 40));
        DaysHeaderPanel.setMinimumSize(new java.awt.Dimension(0, 40));
        DaysHeaderPanel.setPreferredSize(new java.awt.Dimension(0, 40));
        MonthPanel.add(DaysHeaderPanel);

        java.awt.GridLayout layout = new java.awt.GridLayout(6, 7);
        DaysPanel.setLayout(layout);

        DaysPanel.setBackground(new java.awt.Color(255, 255, 255));
        MonthPanel.add(DaysPanel);

        MonthViewPanel.add(MonthPanel, java.awt.BorderLayout.CENTER);

        this.thePanel.add(MonthViewPanel);

        //pack();
    }

    private void todayButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        if(!this.calendar.equals(this.today)) {
            this.calendar = (Calendar) this.today.clone();
            this.monthChanged();
        }
    }    
    
    public void showDate(Date date) {
       this.calendar.setTime(date);
       this.selectedDate = (Calendar) this.calendar.clone();
       this.selectedDayItem = null;
       this.monthChanged();       
    }
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        this.calendar.add(Calendar.MONTH, 1);
        this.monthChanged();
    }

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your handling code here:
        this.calendar.add(Calendar.MONTH, -1);
        this.monthChanged();

    }
    
    public class DayItemMouseListener implements java.awt.event.MouseListener {
        public DayItemMouseListener() {
            Color hyperblue = new Color(0,0,255);
        }

        public void mouseClicked(MouseEvent e) {
            DayItem dayitem = (DayItem) e.getSource();
            dayitem.item.buildInspectionFrame();
        }
        
        public void mouseEntered(MouseEvent e) {
            DayItem dayitem = (DayItem) e.getSource();       
            dayitem.highLight();
        }

        public void mouseExited(MouseEvent e) {
            DayItem dayitem = (DayItem) e.getSource();
            dayitem.unHighLight();
        }

        public void mousePressed(MouseEvent e) {
        }

        public void mouseReleased(MouseEvent e) {
        }
        
    }
    
    public class DayItem extends JLabel {
        public DefaultItem item;
        private Date date;
        private Color lastForeground;
        
        public DayItem(DefaultItem item, Date date) {
            super();
            this.item = item;
            this.date = date;
        }
        public void highLight() {
            this.lastForeground = this.getForeground();
            this.setForeground(new Color(0,0,255));
        }
        public void unHighLight() {
            this.setForeground(this.lastForeground);
        }
    }

    public class DayPanel extends JPanel {
        private Date date;
        private JPanel events;
        private JLabel label;
        private JPanel labelPanel;
        
        private DayItemMouseListener dayItemMouseListener;
        
        private Border regularBorder;
        private Border highlightedBorder;
        
        private Font textFont;
        
        public DayPanel(Border regularBorder, Border highlightedBorder) {
            this.regularBorder = regularBorder;
            this.highlightedBorder = highlightedBorder;
            
            this.dayItemMouseListener = new DayItemMouseListener();
            
            this.setLayout(new java.awt.BorderLayout());
            
            labelPanel = new JPanel();

            labelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

            label = new JLabel();
            label.setMaximumSize(new java.awt.Dimension(30, 30));
            
            labelPanel.add(label);
            this.add(labelPanel, java.awt.BorderLayout.NORTH);
            
            events = new JPanel();
            
            events.setLayout(new javax.swing.BoxLayout(events, javax.swing.BoxLayout.Y_AXIS));
            //events.setMaximumSize(new java.awt.Dimension(32768, 100));

            Dimension size = new Dimension(32768, 80);
            this.setMinimumSize(size);
            this.setPreferredSize(size);      
            this.setMaximumSize(size);
            
            this.add(events, java.awt.BorderLayout.CENTER);
            

            this.setBorder(this.regularBorder);   
            
        }
        
        public void repaint2() {
            if(this.label != null) this.label.repaint();
            if(this.events != null) this.events.repaint();
            super.repaint();
        }
        
        public void setDate(Calendar c) {
            this.date = c.getTime();
            
            String dateString = "" + c.get(Calendar.DAY_OF_MONTH);
            this.label.setText(dateString);
        }
        
        public JLabel getLabel() {
            return label;
        }
        
        public JPanel getTextArea() {
            return events;
        }
        
        public void setTextFont(Font font)
        {
            this.textFont = font;
        }
        
        public void addEvent(CalendarItemModel.ModelItem mi) {
            DefaultItem item = mi.getItem();
            
            String text = item.get("SUMMARY");
            if(text == null) text = item.get("Subject");
            if(text == null) text = item.get("name");
            if(text != null) {
                JLabel alabel = new DayItem(item, this.date);
                //alabel.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY,1));
                
                alabel.setFont(this.textFont);
                alabel.setAlignmentX(label.LEFT_ALIGNMENT);
                
                Date date = new Date();
                date.setTime(mi.date);
               

                alabel.setText(text);
                alabel.addMouseListener(this.dayItemMouseListener);

                this.events.add(alabel);
            }
        }
        
        public void clearEvents() {
            events.removeAll();
            this.revalidate();
            this.repaint();
        }
       
        public void setBackground(Color color) {
            super.setBackground(color);
            if(label != null) label.setBackground(color);
            if(events != null) events.setBackground(color);
            if(labelPanel != null) labelPanel.setBackground(color);
        }
        
        public void setBorder(Border border) {
            this.regularBorder = border;  
            super.setBorder(border);
        }

        public void highLight() {  
            super.setBorder(this.highlightedBorder);
        }
        public void unHighLight() {
            super.setBorder(this.regularBorder);
        }    
        
        public void select(CalendarView calendar) {
            if(calendar.selectedDayItem!=null) {
                calendar.selectedDayItem.setBackground(calendar.unselectedDayColor);
            }
            this.setBackground(calendar.selectedDayColor);
            calendar.selectedDayItem = this;            
        }
    }
    
    
    public class DayMouseListener implements java.awt.event.MouseListener {
        CalendarView calendar; 
        public DayMouseListener(CalendarView calendar) {
            this.calendar = calendar;
        }

        public void mouseClicked(MouseEvent e) {

        }
        
        public void mouseEntered(MouseEvent e) {
            DayPanel day = (DayPanel) e.getSource();       
            //day.highLight();
        }

        public void mouseExited(MouseEvent e) {
            DayPanel day = (DayPanel) e.getSource();
            //day.unHighLight();
        }
        


        public void mousePressed(MouseEvent e) {
            DayPanel dayitem = (DayPanel) e.getSource();
            //dayitem.item.buildInspectionFrame();
            dayitem.select(this.calendar);
        }

        public void mouseReleased(MouseEvent e) {
        }
        
    }
    
    private void setupMonthViewPanel() {


        this.highlightedBorder = new LineBorder(this.highlightedBorderColor);
            
        selectedBorder = new LineBorder(selectedBorderColor, 3);
        regularDayBorder = new LineBorder(borderColor);
        
        monthText.setForeground(headerColor);
        yearText.setForeground(headerColor);
        
        Font labelFont = new java.awt.Font("Arial", 0, 14) ;
        Font textFont = new java.awt.Font("Arial", 0, 12) ;
       
        
        
        for(int row=0; row<6; row++) {
            for(int col=0; col<7; col++) {
                int index = col+row*7;
                DayPanel day = new DayPanel(this.regularDayBorder, this.highlightedBorder);
                days[index] = day;
                day.addMouseListener(this.dayMouseListener);
                day.setTextFont(textFont);
                day.getLabel().setFont(labelFont);
                day.getLabel().setForeground(labelColor);
                day.getTextArea().setForeground(textColor);
                day.setBackground(backgroundColor);

                this.DaysPanel.add(day);
            }
        }
        
        Calendar calendar = (Calendar) this.calendar.clone();
        int firstDayOfWeek = calendar.getFirstDayOfWeek();
        DateFormatSymbols dateFormatSymbols = new DateFormatSymbols(locale);
        dayNames = dateFormatSymbols.getShortWeekdays();
        monthNames = dateFormatSymbols.getMonths();
        
        int day = firstDayOfWeek;
        
        Font headerfont = new java.awt.Font("Arial Black", 0, 18) ;
        
        for (int i = 0; i < 7; i++) {
            DayPanel theDay = new DayPanel(null, null);
            this.daysHeader[i] = theDay;
            this.DaysHeaderPanel.add(theDay);
            
            theDay.getLabel().setText(dayNames[day].toUpperCase());
            theDay.getLabel().setFont(headerfont);
            theDay.getLabel().setForeground(headerColor);
            theDay.getLabel().setAlignmentX(thePanel.CENTER_ALIGNMENT);
            theDay.setBackground(backgroundColor);
            
            if (day < 7) day++;
            else day -= 6;
        }
        drawDays();
    }
    
    private void monthChanged() {
        int dayOfMonth = -1;
        if(this.selectedDayItem != null) {
            Date date = this.selectedDayItem.date;
            Calendar tmpCalendar = (Calendar) calendar.clone();
            tmpCalendar.setTime(date);
            dayOfMonth = tmpCalendar.get(Calendar.DAY_OF_MONTH);
            
            this.selectedDate = (Calendar) calendar.clone();
            this.selectedDate.set(Calendar.DAY_OF_MONTH, dayOfMonth);
        }
        this.drawDays();
        
        if(dayOfMonth != -1) {
            
        }
    }
    
    /**
     *  Hides and shows the day buttons.
     */
    protected void drawDays() {
        
        Calendar tmpCalendar = (Calendar) calendar.clone();
        int firstDayOfWeek = tmpCalendar.getFirstDayOfWeek();
        tmpCalendar.set(Calendar.DAY_OF_MONTH, 1);
        
        int firstDay = tmpCalendar.get(Calendar.DAY_OF_WEEK) - firstDayOfWeek;
        if (firstDay < 0) firstDay += 7;
        
        Calendar firstDate = (Calendar) tmpCalendar.clone();
        firstDate.add(Calendar.DATE, -firstDay);

        //int i;
        
        //Date day = tmpCalendar.getTime();
        int n = 0;
        
        tmpCalendar = (Calendar) firstDate.clone();
        Calendar nextDay = (Calendar) tmpCalendar.clone();
        nextDay.add(Calendar.DATE, 1);

        
        while (n<(6*7)) {
            
            DayPanel theDay = this.days[n];
            theDay.setDate(tmpCalendar);
            
            theDay.clearEvents();
            
            if(this.model != null) {
                
                
                java.util.List events = this.model.getEvents(tmpCalendar, nextDay);
                Iterator iter = events.iterator();
                while(iter.hasNext()) {
                    CalendarItemModel.ModelItem mi = (CalendarItemModel.ModelItem) iter.next();
                    
                    DefaultItem item = mi.getItem();
                    //String s = item.get("SUMMARY");
                    theDay.addEvent(mi);
                }
            }
            

            theDay.setVisible(true);
            //theDay.repaint();
            //theDay.validate();
            
            if(tmpCalendar.get(Calendar.MONTH) != calendar.get(Calendar.MONTH)) {
                theDay.setBackground(nextMonthColor);
            } else if(tmpCalendar.get(Calendar.DAY_OF_WEEK) == 1 || tmpCalendar.get(Calendar.DAY_OF_WEEK) == 7) {
                theDay.setBackground(weekendColor);
            } else {
                theDay.setBackground(backgroundColor);
            }
            
            
            
            if (tmpCalendar.get(Calendar.DAY_OF_YEAR) == today.get(Calendar.DAY_OF_YEAR) &&
                tmpCalendar.get(Calendar.YEAR) == today.get(Calendar.YEAR)) {
                theDay.setBorder(selectedBorder);                
            } else {
                theDay.setBorder(regularDayBorder);
            }
            
            if (tmpCalendar.get(Calendar.DAY_OF_YEAR) == this.selectedDate.get(Calendar.DAY_OF_YEAR) &&
                tmpCalendar.get(Calendar.YEAR) == this.selectedDate.get(Calendar.YEAR)) {
                theDay.select(this);
            }

            n++;
            tmpCalendar.add(Calendar.DATE, 1);
            nextDay.add(Calendar.DATE, 1);
            
        }
        
        //for (int k = n + i + 7; k < 49; k++) {
        //    days[k].setVisible(false);
        //   days[k].setText("");
        //}
        
        monthText.setText("" + this.monthNames[calendar.get(Calendar.MONTH)]);
        yearText.setText("" + calendar.get(Calendar.YEAR));

        this.thePanel.revalidate();
        this.thePanel.repaint();
        //this.thePanel.validate();
    }
    
    public void calendarEventsChanged() {
        // we need to redraw!
        // this.repaint();
        this.monthChanged();
    }    
    
    private javax.swing.JPanel thePanel;
    private javax.swing.JButton prevButton;
    private javax.swing.JPanel DaysHeaderPanel;
    private javax.swing.JLabel yearText;
    private javax.swing.JPanel monthHeaderPanel;
    private javax.swing.JPanel DaysPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel MonthViewPanel;
    private javax.swing.JPanel MonthPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel monthText;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton todayButton;
    
}
