/*
 * DebugFrame.java
 *
 * Created on January 11, 2003, 12:07 PM
 */

package simpleimap;

import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.text.*;
import javax.swing.*;
import javax.swing.border.*;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  hassan
 */
public class DebugFrame extends javax.swing.JFrame {
    private SimpleDateFormat date_formatter;
    private MyListModel model;
    private javax.swing.JTextArea allLog;
    
    
    /** Creates new form DebugFrame */
    public DebugFrame() {
        initComponents();
        
        //this.date_formatter = new SimpleDateFormat("yyyy.MM.dd HH:mm:ss");

        model = new MyListModel();
        threadList.setModel(model);

        this.allLog = new javax.swing.JTextArea();
        model.add("ALL", this.allLog);
        logScrollPane.setViewportView(this.allLog);

    }

    
    public class MyListModel extends javax.swing.AbstractListModel {
        LinkedList strings;
        Hashtable htable;
        
        public MyListModel() {
            this.strings = new LinkedList();
            this.htable = new Hashtable();
        }
        
        public class MyListModelObject {
            String title;
            Object data;
            
            MyListModelObject(String title, Object data) {
                this.title = title;
                this.data = data;
            }
            
        }
        
        public MyListModelObject add(String title, Object data) {
            MyListModelObject obj = new MyListModelObject(title, data);
            this.htable.put(title, obj);
            this.strings.add(obj);
            int n = this.strings.size();
            this.fireIntervalAdded(this, n-1, n); 
            return obj;
        }
        
        
        public int getSize() { 
            return strings.size(); 
        }
        
        public MyListModelObject get(String threadName) {
            MyListModelObject obj = (MyListModelObject) this.htable.get(threadName);
            return obj;
        }
        
        public MyListModelObject getObjAt(int i) {   
            MyListModelObject obj = (MyListModelObject) strings.get(i);
            return obj;
        }
        
        public Object getElementAt(int i) { 
            MyListModelObject obj = (MyListModelObject) strings.get(i);
            
            return obj.title;
        }
    }
    
    
    
   
     private class AddDebugLineRunnable implements Runnable {
         int level;
         String line;
         String threadName;
         AddDebugLineRunnable(int level, String line) {
             this.level = level;
             this.line = line;
             Thread thread = Thread.currentThread();
             this.threadName = thread.getName();
             if(!threadName.startsWith("AWT-")) threadName += " : " + thread.hashCode();

         }
         public void run() {
            awt_thread_debug(level,line, threadName);    
         }
     }
     public void debug(int level, String line) {
        SwingUtilities.invokeLater(new AddDebugLineRunnable(level,line));
     }
   
     
     // this touches the GUI, so it can only occur in the AWT thread...
     public void awt_thread_debug(int level, String line, String threadName) {
       
        
        MyListModel.MyListModelObject obj = this.model.get(threadName);
        JTextArea log;
        if(obj == null) {
            log = new javax.swing.JTextArea();
            
            obj = this.model.add(threadName, log);
        } else {
            log = (JTextArea) obj.data;
        }
        
        
        
        Date now = new Date();
        //String datestr = this.date_formatter.format(now);
        String datestr = now.toString();
        
        this.allLog.append("[" + threadName + " - " + datestr + "] " + line + "\n");

        log.append("[" + datestr + "] " + line + "\n");
        
        Component curComponent = logScrollPane.getViewport().getView();
        if (curComponent == this.allLog || curComponent == log) {
           scrollToBottom();
        }
     }

     private void scrollToBottom() {
         JScrollBar vertsb = logScrollPane.getVerticalScrollBar();
         //vertsb.setValue(vertsb.getMaximum());
     }
     
     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        threadList = new javax.swing.JList();
        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Debug");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(740, 600));
        jSplitPane1.setDividerLocation(160);
        jSplitPane1.setDividerSize(5);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(150, 32767));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 400));
        threadList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "thread 1", "thread 2", "thread 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        threadList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        threadList.setMaximumSize(new java.awt.Dimension(150, 32767));
        threadList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                threadListMouseReleased(evt);
            }
        });

        jScrollPane2.setViewportView(threadList);

        jSplitPane1.setLeftComponent(jScrollPane2);

        logScrollPane.setViewportBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
        logTextArea.setEditable(false);
        logTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        logTextArea.setRows(10);
        logScrollPane.setViewportView(logTextArea);

        jSplitPane1.setRightComponent(logScrollPane);

        jPanel1.add(jSplitPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void threadListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threadListMouseReleased
        // Add your handling code here:
        int n = this.threadList.getSelectedIndex();
        if (n > 0) {
            MyListModel.MyListModelObject obj = this.model.getObjAt(n);

            JTextArea log = (JTextArea) obj.data;

            logScrollPane.setViewportView(log);
            scrollToBottom();
        }
        
    }//GEN-LAST:event_threadListMouseReleased
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        WinterMute.exitApplication();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DebugFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList threadList;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane logScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
