/*
 * Wintermute - Personal Data Organizer
 * 
 * Copyright (C) 2002, by David Jeske
 *
 * Written by David Jeske <jeske@neotonic.com>. 
 *
 * CONFIDENTIAL : This is confidential internal source code. Redistribution
 *   is strictly forbidden.
 */

/*
 * EmailView.java
 *
 * Created on October 29, 2002, 8:06 AM
 */

package simpleimap;
import javax.swing.table.*;
import java.awt.Rectangle;
import java.util.*;

/**
 *
 * @author  David Jeske
 */
public class EmailView extends javax.swing.JPanel {
    DefaultItem message;
    
    /** Creates new form EmailView */
    public EmailView() {
        initComponents();
        relatedInfoEditorPane.setContentType("text/html");
        
    }
    
    public void setMessage(DefaultItem msg) {
        this.message = msg;
        System.out.println("EmailView:setMessage()");

        if (msg == null) {
            emailContentView.setText("");
        } else {
            DefaultTableModel hdrmdl = (DefaultTableModel)emailHeaderTableView.getModel();
            hdrmdl.setValueAt(msg.get("From"),0,1); // From
            hdrmdl.setValueAt(msg.get("Subject"),1,1); // Subject
            hdrmdl.setValueAt(msg.get("To"),2,1); // To
            
            // clear the view immediately
            emailContentView.setText("");   
            repaint();
            
            byte[] data = msg.getData();
            
            if (data != null) {
                try {
                    emailContentView.setText((String)new String(data,"US-ASCII"));
                } catch (java.io.UnsupportedEncodingException e) {
                    emailContentView.setText("");   
                }           
            }
            //Rectangle rect = new Rectangle();
            //rect.setBounds(0, 1,1,1);
            //emailContentView.scrollRectToVisible(rect);
            emailContentView.setCaretPosition(0);
        }
        
        
        // print out related items!!!
        List related_items = msg.getRelatedItems(new ItemRelation("email","contact"));
        Iterator itr = related_items.iterator();
        System.out.println("Related OIDs:");
        String info = "<html><body>";
        while (itr.hasNext()) {
            DefaultItem r_item = (DefaultItem)itr.next();
            info += "<b>oid:</b>" + r_item.get_oid() + "<br>";
            info += "<b>email:</b> " + r_item.get("email") + "<br>";
            info += "<b>name:</b> " + r_item.get("name") + "<br>";
            info += "<i>contact:email</i><b>:</b> " + r_item.getRelatedItemOIDs(new ItemRelation("contact","email")).size();
            info += "<br><br>";
            
        }
        info += "</body></html>";
        
        relatedInfoEditorPane.setText(info);
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSplitPane1 = new javax.swing.JSplitPane();
        emailPanel = new javax.swing.JPanel();
        emailHeaderTableView = new javax.swing.JTable();
        emailScrollView = new javax.swing.JScrollPane();
        emailContentView = new javax.swing.JEditorPane();
        relatedItemPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatedInfoEditorPane = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);
        emailPanel.setLayout(new java.awt.BorderLayout());

        emailHeaderTableView.setBackground(new java.awt.Color(204, 204, 204));
        emailHeaderTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"From", null},
                {"Subject", null},
                {"To", null},
                {null, null}
            },
            new String [] {
                "Header", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        emailHeaderTableView.setGridColor(new java.awt.Color(204, 204, 204));
        emailPanel.add(emailHeaderTableView, java.awt.BorderLayout.NORTH);

        emailContentView.setEditable(false);
        emailContentView.setMinimumSize(new java.awt.Dimension(0, 0));
        emailScrollView.setViewportView(emailContentView);

        emailPanel.add(emailScrollView, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(emailPanel);

        relatedItemPanel.setLayout(new java.awt.BorderLayout());

        relatedInfoEditorPane.setEditable(false);
        relatedInfoEditorPane.setMinimumSize(new java.awt.Dimension(10, 5));
        jScrollPane1.setViewportView(relatedInfoEditorPane);

        relatedItemPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(relatedItemPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane emailContentView;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JEditorPane relatedInfoEditorPane;
    private javax.swing.JPanel relatedItemPanel;
    private javax.swing.JTable emailHeaderTableView;
    private javax.swing.JScrollPane emailScrollView;
    // End of variables declaration//GEN-END:variables
    
}
