/*
 * ICal_ImportWizard.java
 *
 * Created on November 18, 2002, 3:05 PM
 */

package simpleimap;

import java.net.*;
import java.util.*;
import java.io.*;
import org.netbeans.lib.awtextra.*;


/**
 *
 * @author  hassan
 */
public class ICal_ImportWizard extends javax.swing.JDialog {
        private DefaultItem item;
        private ICalListModel model;

    /** Creates new form ICal_ImportWizard */
    public ICal_ImportWizard(java.awt.Frame parent, boolean modal, DefaultItem item) {
        super(parent, modal);
        this.item = item;
        initComponents();
        
        this.model = new ICalListModel();
        this.model.add("US Holidays", "http://ical.mac.com/ical/US32Holidays.ics");
        this.model.add("Movies", "http://ical.mac.com/ical/Movies.ics");
        this.model.add("Moon Phases", "http://www.la-grange.net/2002/09/13-MoonPhase.ics");
        this.model.add("DVD Releases", "http://ical.mac.com/ical/DVDs.ics" );
        
        this.model.add("Enterprise Schedule", "http://homepage.mac.com/sebimeyer/.calendars/Enterprise32Season322.ics");
        this.model.add("Pagen Holidays", "http://ical.mac.com/kyrina/Pagan32Holidays.ics");

        
        this.iCalList.setModel(model);
        
    }
    
    
    public class ICalListModel extends javax.swing.AbstractListModel {
        LinkedList strings;
        
        public ICalListModel() {
            this.strings = new LinkedList();
        }
        
        public class ICalListObject {
            String title;
            String data;
            ICalListObject(String title, String data) {
                this.title = title;
                this.data = data;
            }
            
        }
        
        public void add(String title, String url) {
            ICalListObject obj = new ICalListObject(title, url);
            strings.add(obj);
        }
        
        
        public int getSize() { 
            return strings.size(); 
        }
        
        public ICalListObject getObjAt(int i) {   
            ICalListObject obj = (ICalListObject) strings.get(i);
            return obj;
        }
        
        public Object getElementAt(int i) { 
            ICalListObject obj = (ICalListObject) strings.get(i);
            
            return obj.title;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        iCalList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        urlField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.add(cancelButton);

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        jPanel1.add(importButton);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 440, 40));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        iCalList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "http://ical.mac.com/ical/US32Holidays.ics", "http://ical.mac.com/ical/Movies.ics", "http://ical.mac.com/ical/DVDs.ics" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        iCalList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        iCalList.setVisibleRowCount(10);
        jScrollPane1.setViewportView(iCalList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 200));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        urlField.setColumns(35);
        jPanel3.add(urlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("iCal URL:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 430, 50));

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    
    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // Add your handling code here:
        
        try {
            int row = this.iCalList.getSelectedIndex();
            if(row != -1) {
                ICalListModel.ICalListObject obj = (ICalListModel.ICalListObject) this.model.getObjAt(row);
                //String url = this.urlField.getText();
                ItemICal cal = (ItemICal) WinterMute.my_db.newItem(null, "ItemICal", "ICal: " + obj.title);
                cal.put("url", obj.data);
                item.addChild(cal);
            } else {
                String url = this.urlField.getText();
                if(url.length() > 0) {
                    ItemICal cal = (ItemICal) WinterMute.my_db.newItem(null, "ItemICal", "ICal: " + url);
                    cal.put("url", url);
                    item.addChild(cal);  
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("calendar parse Failed");
        }
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_importButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
  //      new ICal_ImportWizard(new javax.swing.JFrame(), true).show();
  //  }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField urlField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton importButton;
    private javax.swing.JList iCalList;
    // End of variables declaration//GEN-END:variables
    
}
