/*
 * MySQL_ImportWizard.java
 *
 * Created on November 17, 2002, 10:39 PM
 */

package simpleimap;

import java.sql.*;
import java.util.*;

/**
 *
 * @author  hassan
 */
public class MySQL_ImportWizard extends javax.swing.JDialog {
     private DefaultItem item;
     private MySQLSyncThread sync_thread;
   
    /** Creates new form MySQL_ImportWizard */
    public MySQL_ImportWizard(java.awt.Frame parent, boolean modal, DefaultItem item) {
        super(parent, modal);
        this.item = item;

        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        connectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hostnameField = new javax.swing.JTextField();
        databaseField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        getContentPane().add(connectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel1.setText("Hostname");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setText("Database");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        getContentPane().add(hostnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, -1));

        getContentPane().add(databaseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, -1));

        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, -1));

        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, -1));

        jLabel5.setText("MySQL Connection Wizard");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    
    class MySQLSyncThread extends Thread {
        private DefaultItem item;
        private String hostname;
        private String db;
        private String username;
        private String password;
        
         MySQLSyncThread(DefaultItem item, String hostname, String db, String username, String password) {
           this.hostname = hostname;
           this.db = db;
           this.username = username;
           this.password = password;
           this.item = item;
           this.setDaemon(true);
         }

         public void run() {    
            Connection conn = null;
            Statement stmt = null;
            PreparedStatement pStmt = null;

           try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
           } catch (Exception e) {
                throw new RuntimeException("driver load failed!");
           }

            try {
                String dburl = "jdbc:mysql://" + hostname + "/" + db + "?user=" + username + "&password=" + password;
                conn = DriverManager.getConnection(dburl);
                stmt = conn.createStatement();

                DefaultItem newdb = WinterMute.my_db.newItem(null, "Default", "mysql:" + db + "@" + hostname);    
                item.relateTo(new ItemRelation("parent","child"),newdb);

                ResultSet tables_rs = stmt.executeQuery("show tables");
                List tables = new LinkedList();
                while(tables_rs.next()) {
                    String tablename = tables_rs.getString(1);
                    tables.add(tablename);
                }

                Iterator iter = tables.iterator();

                while(iter.hasNext()) {

                    String tablename = (String) iter.next();
                    Debug.debug("table=" + tablename);

                    DefaultItem newtable = WinterMute.my_db.newItem(null, "Default", tablename);    
                    newdb.addChild(newtable);

                    ResultSet rs = stmt.executeQuery("SELECT * from " + tablename);
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int numberOfColumns = rsmd.getColumnCount();

                    while (rs.next()) {
                        DefaultItem newitem = WinterMute.my_db.newItem(null, "Default", null);    
                        newtable.addItem(newitem);

                        for(int i=1; i<=numberOfColumns; i++) {
                            String col_name = rsmd.getColumnLabel(i);
                            Object value = rs.getObject(i);
                            if (value != null) {
                                newitem.put(col_name, value.toString());
                            }
                        }
                        
                        //Debug.debug("import item:" + newitem);
                    }  
                    int foo = 1;
                }
            } catch (Exception e) {
                e.printStackTrace();
                
                throw new RuntimeException("mysql select failed!"); 
            } finally {
                if (pStmt != null) {
                    try {
                        pStmt.close();
                    } catch (SQLException sqlEx) { /* ignore */
                    }
                }
                if (stmt != null) {
                    try {
                        stmt.close();
                    } catch (SQLException sqlEx) { /* ignore */
                    }
                }
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException sqlEx) { /* ignore */
                    }
                }
            }
        }
    }
    
    
    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        sync_thread = new MySQLSyncThread(this.item, hostnameField.getText(), databaseField.getText(), 
                                          usernameField.getText(), passwordField.getText());
        sync_thread.start();
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_connectButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
    //    new MySQL_ImportWizard(new javax.swing.JFrame(), true).show();
   // }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField hostnameField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField databaseField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    
}
