/*
 * NewSyncWizard.java
 *
 * Created on January 6, 2003, 12:36 PM
 */

package simpleimap;

import  java.util.prefs.*;

/**
 *
 * @author  hassan
 */
public class NewSyncWizard extends javax.swing.JFrame {
    
    /** Creates new form NewSyncWizard */
    public NewSyncWizard() {
        initComponents();
        this.readDefaultValues();
        
    }
    
    private void readDefaultValues() {
        Preferences prefs = Preferences.systemNodeForPackage(this.getClass());

        loginField.setText(prefs.get("NewSyncWizard.loginField", ""));
        passwordField.setText(prefs.get("NewSyncWizard.passwordField", ""));
    }
    
    private void setDefaultValues() {
        Preferences prefs = Preferences.systemNodeForPackage(this.getClass());

        prefs.put("NewSyncWizard.loginField", loginField.getText());
        prefs.put("NewSyncWizard.passwordField", passwordField.getText());

        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setText("New Sync Wizard");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 1, 3, 1)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(new javax.swing.border.TitledBorder("Yahoo Account Information"));
        jPanel4.setMinimumSize(new java.awt.Dimension(240, 100));
        jPanel4.setName("null");
        jPanel4.setPreferredSize(new java.awt.Dimension(240, 100));
        loginLabel.setText("Username:");
        jPanel4.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jPanel4.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, -1));

        passwordLabel.setText("Password:");
        jPanel4.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jPanel4.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, -1));

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createButton.setText("Ok");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jPanel6.add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel6.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jPanel5.add(jPanel6);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // Add your handling code here:
        
        this.setDefaultValues();
        
        String login = loginField.getText();
        
        DefaultItem server = WinterMute.my_db.newItem(null, ItemYahooSync.TypeID, login + "@yahoo.com");
        server.put("login", loginField.getText());
        server.put("password", passwordField.getText());
        
        DefaultItem rootItem = WinterMute.my_db.getItem(0);
        rootItem.addChild(server);
        
        this.dispose();
        
    }//GEN-LAST:event_createButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new NewSyncWizard().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loginField;
    private javax.swing.JButton createButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables
    
}
