/*
 * Wintermute - Personal Data Organizer
 *
 * Copyright (C) 2002, by David Jeske and Neotonic Software Corporation.
 *
 * Written by David Jeske <jeske@neotonic.com>.
 *
 * CONFIDENTIAL : This is confidential internal source code. Redistribution
 *   is strictly forbidden.
 */

/*
 * ColorSwitch.java
 *
 * Created on October 27, 2002, 1:52 PM
 */

package packrat;

import javax.swing.*;
import javax.swing.event.*;
import javax.swing.tree.*;
import javax.swing.table.*;

import packrat.*;

import java.io.*;
import java.lang.*;
import java.util.*;

/**
 *
 *
 * @author  David Jeske
 */

public class PackratFrame extends javax.swing.JFrame {
 

    
    private DataStore ds;
    private javax.swing.tree.DefaultMutableTreeNode treetop;
    private javax.swing.tree.DefaultTreeModel treemodel;
    private javax.swing.table.DefaultTableModel emptypropertytablemodel;
    
    private javax.swing.table.DefaultTableModel emptyitemtablemodel;
   
    
    /** Creates new form ColorSwitch */
    public PackratFrame() { 
        ds = new DataStore();
        
        treetop = ds.ciTop.makeTreeModel();
        initComponents();
        
        treemodel = ((DefaultTreeModel)jTree1.getModel());
        treemodel.setRoot(treetop);
        
        emptypropertytablemodel = (DefaultTableModel) propertyListTableView.getModel();
        emptyitemtablemodel = (DefaultTableModel) propertyListTableView.getModel();
        
        
        ListSelectionModel rowSM = itemTableView.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //Ignore extra messages.
                if (e.getValueIsAdjusting()) return;
        
                ListSelectionModel lsm =
                    (ListSelectionModel)e.getSource();
                if (lsm.isSelectionEmpty()) {
                    //no rows are selected
                } else {
                    int selectedRow = lsm.getMinSelectionIndex();
                    //selectedRow is selected
                    System.out.println("Row selected" + selectedRow);
                }
            }
        });
        

        
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ClassEditor = new javax.swing.JPanel();
        ciName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ciSaveButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        propertyListTableView = new javax.swing.JTable();
        DataEditor = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        itemListScrolPane = new javax.swing.JScrollPane();
        itemTableView = new javax.swing.JTable();
        itemDetailsScrollPane = new javax.swing.JScrollPane();
        itemDetailsTableView = new javax.swing.JTable();
        toolBarPanel = new javax.swing.JPanel();
        jNewCatButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        saveTreeMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("Menu");
        jMenuItem1.setText("Item");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setTitle("Packrat");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTree1.setRootVisible(false);
        jTree1.setShowsRootHandles(true);
        jTree1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTree1KeyTyped(evt);
            }
        });

        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        ClassEditor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ciName.setEnabled(false);
        ClassEditor.add(ciName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 210, -1));

        jLabel1.setText("Name");
        ClassEditor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        ciSaveButton.setText("save");
        ciSaveButton.setEnabled(false);
        ciSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciSaveButtonActionPerformed(evt);
            }
        });

        ClassEditor.add(ciSaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        propertyListTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(propertyListTableView);

        ClassEditor.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 170));

        jTabbedPane1.addTab("Data Editor", ClassEditor);

        DataEditor.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        itemListScrolPane.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                itemListScrolPaneCaretPositionChanged(evt);
            }
        });

        itemTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item"
            }
        ));
        itemListScrolPane.setViewportView(itemTableView);

        jSplitPane2.setTopComponent(itemListScrolPane);

        itemDetailsTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itemDetailsScrollPane.setViewportView(itemDetailsTableView);

        jSplitPane2.setBottomComponent(itemDetailsScrollPane);

        DataEditor.add(jSplitPane2, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addTab("Items", DataEditor);

        jSplitPane1.setRightComponent(jTabbedPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        toolBarPanel.setLayout(new javax.swing.BoxLayout(toolBarPanel, javax.swing.BoxLayout.X_AXIS));

        jNewCatButton.setText("New");
        jNewCatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewCatButtonActionPerformed(evt);
            }
        });

        toolBarPanel.add(jNewCatButton);

        getContentPane().add(toolBarPanel, java.awt.BorderLayout.NORTH);

        jMenu2.setText("File");
        saveTreeMenuItem.setText("SaveTree");
        saveTreeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTreeMenuItemActionPerformed(evt);
            }
        });

        jMenu2.add(saveTreeMenuItem);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents

    private void itemListScrolPaneCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_itemListScrolPaneCaretPositionChanged
        // Add your handling code here:

        
    }//GEN-LAST:event_itemListScrolPaneCaretPositionChanged

    private void saveTreeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTreeMenuItemActionPerformed
        // Add your handling code here:
        ds.save();
        
    }//GEN-LAST:event_saveTreeMenuItemActionPerformed

    private void jNewCatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewCatButtonActionPerformed
        // Add your handling code here:
        
        
    }//GEN-LAST:event_jNewCatButtonActionPerformed

    private void ciSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciSaveButtonActionPerformed
        // Add your handling code here:
       DefaultMutableTreeNode node = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
       
       if (node == null) {
         disableEditor(); 
         return;
       }
       
       ClassificationInfo ci = (ClassificationInfo) node.getUserObject();
       ci.name = ciName.getText();
       treemodel.nodeChanged(node);
       
    }//GEN-LAST:event_ciSaveButtonActionPerformed

    private void disableEditor() {
       ciName.setText("");
       ciName.setEnabled(false); 
       ciSaveButton.setEnabled(false);
       propertyListTableView.setModel(emptypropertytablemodel);
       itemTableView.setModel(emptyitemtablemodel);
    }
    
    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
       // the tree item was selected, so show the property editor for this item
       DefaultMutableTreeNode node = (DefaultMutableTreeNode)jTree1.getLastSelectedPathComponent();
       
       if (node == null) {
         disableEditor(); 
         return;
       }
       
       ClassificationInfo ci = (ClassificationInfo) node.getUserObject();

       ciName.setText(ci.name);
       ciName.setEnabled(true);
       ciSaveButton.setEnabled(true);
       propertyListTableView.setModel(ci.makeTableModelForProperties());
       itemTableView.setModel(ci.makeTableModelForItems());
       
    }//GEN-LAST:event_jTree1ValueChanged

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_jTree1MouseClicked

    private void jTree1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTree1KeyTyped
        // Add your handling code here:
    }//GEN-LAST:event_jTree1KeyTyped
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // JavaMail and SSL
        // http://www.javaworld.com/javatips/jw-javatip115.html
        /*
        java.security.Security.addProvider( new com.sun.net.ssl.internal.ssl.Provider());
        
        Properties props = System.getProperties();
        if (true) {
            // custom factory to accept all certificates
           //  Security.setProperty( "ssl.SocketFactory.provider", "packrat.DummySSLSocketFactory");    
        } 
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
        // IMAP provider
        props.setProperty( "mail.imap.socketFactory.class", SSL_FACTORY);

        // POP3 provider
        props.setProperty( "mail.pop3.socketFactory.class", SSL_FACTORY);

        // NNTP provider (if any)
        // props.setProperty( "mail.nntp.socketFactory.class", SSL_FACTORY);

        // IMAP provider
        props.setProperty( "mail.imap.port", "993");
        props.setProperty( "mail.imap.socketFactory.port", "993");
            
        // POP3 provider
        props.setProperty( "mail.pop3.port", "995");
        props.setProperty( "mail.pop3.socketFactory.port", "995");

        Session session = Session.getInstance(props);
        
        */
        new PackratFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ciSaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel DataEditor;
    private javax.swing.JTable propertyListTableView;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jNewCatButton;
    private javax.swing.JMenuItem saveTreeMenuItem;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel toolBarPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane itemDetailsScrollPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField ciName;
    private javax.swing.JTable itemDetailsTableView;
    private javax.swing.JPanel ClassEditor;
    private javax.swing.JTable itemTableView;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JScrollPane itemListScrolPane;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    
    
    
}

